FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY *.go ./
RUN go build -o /hello 

FROM scratch
WORKDIR /
COPY --from=builder /hello /hello
ENTRYPOINT [ "/hello" ]
