### Create Asset
POST http://localhost:3000/api/assets
Content-Type: application/json
{
    "id": "asset1",
    "symbol": "MGLU3",
    "price": 10,
}

### List Assets
GET http://localhost:3000/api/assets

### Create Order
POST http://localhost:3000/api/assets

### List Order
GET http://localhost:3000/api/orders
