version: '3'

services:

  app:
    build:
      context: .
    container_name: app
    ports:
      - "3000:3000"
    entrypoint: wait-for db:3306 -t 40 -- npm start
    networks:
      - node-network
    volumes:
      - ./src:/home/node/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    networks:
      - node-network
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  node-network:
    driver: bridge