name: ci-golang-workflow
on:
  pull_request:
    branches:
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ci/go
    strategy:
      matrix:
        go: ["1.14", "1.15"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go
